name: 'run'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: main
        env:

          netease_username: ${{ secrets.netease_username }}
          netease_password: ${{ secrets.netease_password }}
    
          wps_userid: ${{ secrets.wps_userid }}
        run: |
          python3 ./Cloud189Checkin/C189CheckinForSCF.py
          python3 ./FF14Checkin/FF14CheckinForSCF.py
          python3 ./Checkin52pj/Checkin52pjForSCF.py
          python3 ./smzdmCheckin/smzdmCheckinForSCF.py
          python3 ./NetEase_Music_daily/NetEase_Music_dailyForSCF.py
          python3 ./NoteyoudaoCheckin/NoteYoudaoForSCF.py
          python3 ./V2EX/v2ex.py
          python3 ./Enshan/Enshan.py
          python3 ./Zhiyou/zhiyou.py
          python3 ./WPS/wps_invite.py
